name: Lint the code
on:
  workflow_dispatch
jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Lint the code
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}